-- Drop the AUTHORS table if it exists
DROP TABLE AUTHORS;
-- Create the AUTHORS table
Create TABLE AUTHORS
(
    AUTHORID INT NOT NULL GENERATED ALWAYS AS IDENTITY,

    FIRSTNAME VARCHAR(255) NOT NULL,

    LASTNAME VARCHAR(255) NOT NULL,

    PRIMARY KEY (AUTHORID)
);
-- Insert sample data into the AUTHORS table
INSERT INTO AUTHORS (FIRSTNAME, LASTNAME) VALUES
('Paul', 'Deitel'),
('Michael', 'Negnevitsky'),
('Daneil', 'Yang');


-- Drop the TITLES table if it exists
DROP TABLE TITLES;
-- Create the TITLES table
Create TABLE TITLES
(
    ISBN VARCHAR(13) NOT NULL,

    TITLE VARCHAR(255) NOT NULL,

    EDITIONNUMBER INT NOT NULL,

    COPYRIGHT VARCHAR(4) NOT NULL,

    PRIMARY KEY (ISBN)
);

-- Insert sample data into the TITLES table
INSERT INTO TITLES (ISBN, TITLE, EDITIONNUMBER, COPYRIGHT) VALUES
('132151006', 'Internet & World Wide Web How to Program', 5, '2012'),
('9781292730851', 'ARTIFICIAL INTELLIGENCE: A GUIDE TO INTELLIGENT SYSTEMS', 4, '2025'),
('9789813351936', 'INTRODUCTION TO PYTHON PROGRAMMING', 1, '2024');

-- Drop the AUTHORISBN table if it exists
DROP TABLE AUTHORISBN;
-- Create the AUTHORISBN table
CREATE TABLE AUTHORISBN
(
    AUTHORID INT NOT NULL,

    ISBN VARCHAR(13) NOT NULL,

    FOREIGN KEY (AUTHORID) REFERENCES AUTHORS(AUTHORID),

    FOREIGN KEY (ISBN) REFERENCES TITLES(ISBN)

);

INSERT INTO AUTHORISBN (AUTHORID, ISBN) VALUES
(1, '132151006'),
(2, '9781292730851'),
(3, '9789813351936');